import {
  ArrowDownUp,
  BanknoteArrowUp,
  BriefcaseBusiness,
  Bus,
  Calculator,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  Car,
  ChartCandlestick,
  ChartColumn,
  ChartLine,
  ChartNoAxesColumnIncreasing,
  ChartPie,
  ChartSpline,
  CircleCheckBig,
  CircleDollarSign,
  ClipboardList,
  Coins,
  Compass,
  CreditCard,
  Flag,
  Gift,
  GraduationCap,
  HandCoins,
  Heart,
  House,
  HousePlug,
  Inbox,
  Landmark,
  Laptop,
  Leaf,
  LifeBuoy,
  Lightbulb,
  PartyPopper,
  PiggyBank,
  Plane,
  Popcorn,
  ReceiptText,
  Repeat,
  Scale,
  Settings,
  ShieldCheck,
  ShoppingBasket,
  Target,
  TreePalm,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Umbrella,
  UsersRound,
  Wallet,
  WalletCards,
  Wrench,
  type LucideIcon,
} from 'lucide-react';
import type { PictureName } from './pictures';

/** The line-icon twin of each illustration, for phones, where the set is drawn in the nav's glyph style. Logos have none. */
export const GLYPH: Partial<Record<PictureName, LucideIcon>> = {
  'welcome-plan': ClipboardList,
  'welcome-explore': Compass,

  'nav-home': House,
  'nav-income': BanknoteArrowUp,
  'nav-home-bills': HousePlug,
  'nav-living': ShoppingBasket,
  'nav-transport': Bus,
  'nav-finance': Umbrella,
  'nav-leisure': Popcorn,
  'nav-planned': CalendarPlus,
  'nav-savings': PiggyBank,
  'nav-accounts': WalletCards,
  'nav-planning': CalendarDays,
  'nav-insights': ChartPie,
  'nav-settings': Settings,

  'stat-safe-to-spend': Wallet,
  'stat-income': BanknoteArrowUp,
  'stat-cost': ReceiptText,
  'stat-saving': PiggyBank,
  'stat-bank': Landmark,

  'account-everyday': CreditCard,
  'account-salary': BriefcaseBusiness,
  'account-savings': PiggyBank,
  'account-emergency': LifeBuoy,
  'account-joint': UsersRound,
  'account-cash': Coins,
  'account-investment': ChartCandlestick,
  'account-other': CircleDollarSign,

  'goal-shield': ShieldCheck,
  'goal-home': House,
  'goal-palmtree': TreePalm,
  'goal-car': Car,
  'goal-laptop': Laptop,
  'goal-plane': Plane,
  'goal-gift': Gift,
  'goal-heart': Heart,
  'goal-graduation': GraduationCap,
  'goal-wrench': Wrench,
  'goal-piggy': PiggyBank,
  'goal-trending': TrendingUp,
  'goal-target': Target,
  'goal-leaf': Leaf,

  'card-where-money-goes': ChartPie,
  'card-position': Scale,
  'card-goals': Flag,
  'card-income-stability': HandCoins,
  'card-upcoming': CalendarClock,
  'card-income-stopped': TrendingDown,
  'card-resilience': LifeBuoy,
  'card-afford': Calculator,
  'card-income-change': ArrowDownUp,
  'card-per-day': CalendarDays,
  'card-expensive-months': ChartColumn,
  'card-subscriptions': Repeat,
  'card-car-cost': Car,
  'card-largest': ChartNoAxesColumnIncreasing,
  'card-savings-projection': ChartSpline,
  'card-allocation': ChartLine,

  'state-empty': Inbox,
  'state-success': CircleCheckBig,
  'state-warning': TriangleAlert,
  'state-tip': Lightbulb,
  'state-celebrate': PartyPopper,
};
